server:
  host: "0.0.0.0"   # 0.0.0.0 allows access from other computers on the network
  port: 9889       

location:
  name: "CASM"
  latitude: 37.234167     
  longitude: -118.283333  
  elevation: 1206.84      

antenna:
  beam_fwhm: 100           

sources:
  - name: Cas A
    ra: [23, 23, 24]      
    dec: [58, 48, 54]     
  
  - name: Cyg A
    ra: [19, 59, 28]
    dec: [40, 44, 2]
  
  - name: Tau A
    ra: [5, 34, 31]
    dec: [22, 0, 52]
  
  - name: Vir A
    ra: [12, 30, 49]
    dec: [12, 23, 28]

  - name: B0329+54/J0332+5434
    ra: [3, 32, 59.4096]
    dec: [54, 34, 43.329]

  - name: B1749-28/J1752-2806
    ra: [17, 52, 58.6896]
    dec: [-28, 6, 37.3]

  - name: B0531+21/J0534+2200
    ra: [5, 34, 31.93357]
    dec: [22, 0, 52.1927]

  - name: B0950+08/J0953+0755
    ra: [9, 53, 9.3097]
    dec: [7, 55, 35.75]

  - name: B1642-03/J1645-0317
    ra: [16, 45, 2.0406]
    dec: [-3, 17, 57.819]

  - name: J0341+5711
    ra: [0, 0, 0.0]
    dec: [0, 0, 0.0]

  - name: B2016+28/J2018+2839
    ra: [20, 18, 3.8333]
    dec: [28, 39, 54.212]

  - name: B1929+10/J1932+1059
    ra: [19, 32, 14.057]
    dec: [10, 59, 33.38]

  - name: B0740-28/J0742-2822
    ra: [7, 42, 49.058]
    dec: [-28, 22, 43.76]
    
  - name: B1133+16/J1136+1551
    ra: [11, 36, 3.1198]
    dec: [15, 51, 14.183]


plot:
  refresh_rate: 1000      
  track_hours: 24